export { ReactComponent as shooting_stars_037 } from '../../../assets/illustrations/037-shooting stars.svg';
export { ReactComponent as blimp_001 } from '../../../assets/illustrations/001-blimp.svg';
export { ReactComponent as alien_002 } from '../../../assets/illustrations/002-alien.svg';
export { ReactComponent as universe_003 } from '../../../assets/illustrations/003-universe.svg';
export { ReactComponent as asteroid_004 } from '../../../assets/illustrations/004-asteroid.svg';
export { ReactComponent as planets_005 } from '../../../assets/illustrations/005-planets.svg';
export { ReactComponent as scientistA_006 } from '../../../assets/illustrations/006-scientist.svg';
export { ReactComponent as scientistB_007 } from '../../../assets/illustrations/007-scientist.svg';
export { ReactComponent as dish_008 } from '../../../assets/illustrations/008-dish.svg';
export { ReactComponent as stars_009 } from '../../../assets/illustrations/009-stars.svg';
export { ReactComponent as earth_010 } from '../../../assets/illustrations/010-earth.svg';
export { ReactComponent as rocket_011 } from '../../../assets/illustrations/011-rocket 2.svg';
export { ReactComponent as astronaut_012 } from '../../../assets/illustrations/012-astronaut.svg';
export { ReactComponent as galaxy_013 } from '../../../assets/illustrations/013-galaxy.svg';
export { ReactComponent as globe_014 } from '../../../assets/illustrations/014-globe.svg';
export { ReactComponent as astronaut_015 } from '../../../assets/illustrations/015-astronaut.svg';
export { ReactComponent as jupiter_016 } from '../../../assets/illustrations/016-jupiter.svg';
export { ReactComponent as ufo_017 } from '../../../assets/illustrations/017-ufo 3.svg';
export { ReactComponent as laser_gun_018 } from '../../../assets/illustrations/018-laser gun.svg';
export { ReactComponent as lunar_019 } from '../../../assets/illustrations/019-lunar.svg';
export { ReactComponent as astronaut_020 } from '../../../assets/illustrations/020-astronaut.svg';
export { ReactComponent as mars_021 } from '../../../assets/illustrations/021-mars.svg';
export { ReactComponent as mercury_022 } from '../../../assets/illustrations/022-mercury.svg';
export { ReactComponent as comet_023 } from '../../../assets/illustrations/023-comet.svg';
export { ReactComponent as monitor_024 } from '../../../assets/illustrations/024-monitor.svg';
export { ReactComponent as moon_phase_025 } from '../../../assets/illustrations/025-moon phase.svg';
export { ReactComponent as neptune_026 } from '../../../assets/illustrations/026-neptune.svg';
export { ReactComponent as explore_027 } from '../../../assets/illustrations/027-explore.svg';
export { ReactComponent as planetarium_028 } from '../../../assets/illustrations/028-planetarium.svg';
export { ReactComponent as pluto_029 } from '../../../assets/illustrations/029-pluto.svg';
export { ReactComponent as radar_030 } from '../../../assets/illustrations/030-radar.svg';
export { ReactComponent as report_031 } from '../../../assets/illustrations/031-report.svg';
export { ReactComponent as launchA_032 } from '../../../assets/illustrations/032-launch.svg';
export { ReactComponent as launchB_033 } from '../../../assets/illustrations/033-launch.svg';
export { ReactComponent as satelliteA_034 } from '../../../assets/illustrations/034-satellite.svg';
export { ReactComponent as satelliteB_035 } from '../../../assets/illustrations/035-satellite.svg';
export { ReactComponent as saturn_036 } from '../../../assets/illustrations/036-saturn.svg';
export { ReactComponent as book_038 } from '../../../assets/illustrations/038-book.svg';
export { ReactComponent as eclipse_039 } from '../../../assets/illustrations/039-eclipse.svg';
export { ReactComponent as solar_system_040 } from '../../../assets/illustrations/040-solar system.svg';
export { ReactComponent as flag_041 } from '../../../assets/illustrations/041-flag.svg';
export { ReactComponent as scientist_042 } from '../../../assets/illustrations/042-scientist.svg';
export { ReactComponent as space_shuttle_043 } from '../../../assets/illustrations/043-space shuttle.svg';
export { ReactComponent as astronaut_044 } from '../../../assets/illustrations/044-astronaut.svg';
export { ReactComponent as sputnik_045 } from '../../../assets/illustrations/045-sputnik.svg';
export { ReactComponent as stars_046 } from '../../../assets/illustrations/046-stars.svg';
export { ReactComponent as sun_047 } from '../../../assets/illustrations/047-sun.svg';
export { ReactComponent as telescope_048 } from '../../../assets/illustrations/048-telescope 1.svg';
export { ReactComponent as ufo_049 } from '../../../assets/illustrations/049-ufo.svg';
export { ReactComponent as uranus_050 } from '../../../assets/illustrations/050-uranus.svg';
export { ReactComponent as venus_051 } from '../../../assets/illustrations/051-venus.svg';
export { ReactComponent as bicycle_052 } from '../../../assets/illustrations/052-bicycle.svg';
