export { ReactComponent as shooting_stars_037 } from '../../illustrations/037-shooting stars.svg';
export { ReactComponent as blimp_001 } from '../../illustrations/001-blimp.svg';
export { ReactComponent as alien_002 } from '../../illustrations/002-alien.svg';
export { ReactComponent as universe_003 } from '../../illustrations/003-universe.svg';
export { ReactComponent as asteroid_004 } from '../../illustrations/004-asteroid.svg';
export { ReactComponent as planets_005 } from '../../illustrations/005-planets.svg';
export { ReactComponent as scientistA_006 } from '../../illustrations/006-scientist.svg';
export { ReactComponent as scientistB_007 } from '../../illustrations/007-scientist.svg';
export { ReactComponent as dish_008 } from '../../illustrations/008-dish.svg';
export { ReactComponent as stars_009 } from '../../illustrations/009-stars.svg';
export { ReactComponent as earth_010 } from '../../illustrations/010-earth.svg';
export { ReactComponent as rocket_011 } from '../../illustrations/011-rocket 2.svg';
export { ReactComponent as astronaut_012 } from '../../illustrations/012-astronaut.svg';
export { ReactComponent as galaxy_013 } from '../../illustrations/013-galaxy.svg';
export { ReactComponent as globe_014 } from '../../illustrations/014-globe.svg';
export { ReactComponent as astronaut_015 } from '../../illustrations/015-astronaut.svg';
export { ReactComponent as jupiter_016 } from '../../illustrations/016-jupiter.svg';
export { ReactComponent as ufo_017 } from '../../illustrations/017-ufo 3.svg';
export { ReactComponent as laser_gun_018 } from '../../illustrations/018-laser gun.svg';
export { ReactComponent as lunar_019 } from '../../illustrations/019-lunar.svg';
export { ReactComponent as astronaut_020 } from '../../illustrations/020-astronaut.svg';
export { ReactComponent as mars_021 } from '../../illustrations/021-mars.svg';
export { ReactComponent as mercury_022 } from '../../illustrations/022-mercury.svg';
export { ReactComponent as comet_023 } from '../../illustrations/023-comet.svg';
export { ReactComponent as monitor_024 } from '../../illustrations/024-monitor.svg';
export { ReactComponent as moon_phase_025 } from '../../illustrations/025-moon phase.svg';
export { ReactComponent as neptune_026 } from '../../illustrations/026-neptune.svg';
export { ReactComponent as explore_027 } from '../../illustrations/027-explore.svg';
export { ReactComponent as planetarium_028 } from '../../illustrations/028-planetarium.svg';
export { ReactComponent as pluto_029 } from '../../illustrations/029-pluto.svg';
export { ReactComponent as radar_030 } from '../../illustrations/030-radar.svg';
export { ReactComponent as report_031 } from '../../illustrations/031-report.svg';
export { ReactComponent as launchA_032 } from '../../illustrations/032-launch.svg';
export { ReactComponent as launchB_033 } from '../../illustrations/033-launch.svg';
export { ReactComponent as satelliteA_034 } from '../../illustrations/034-satellite.svg';
export { ReactComponent as satelliteB_035 } from '../../illustrations/035-satellite.svg';
export { ReactComponent as saturn_036 } from '../../illustrations/036-saturn.svg';
export { ReactComponent as book_038 } from '../../illustrations/038-book.svg';
export { ReactComponent as eclipse_039 } from '../../illustrations/039-eclipse.svg';
export { ReactComponent as solar_system_040 } from '../../illustrations/040-solar system.svg';
export { ReactComponent as flag_041 } from '../../illustrations/041-flag.svg';
export { ReactComponent as scientist_042 } from '../../illustrations/042-scientist.svg';
export { ReactComponent as space_shuttle_043 } from '../../illustrations/043-space shuttle.svg';
export { ReactComponent as astronaut_044 } from '../../illustrations/044-astronaut.svg';
export { ReactComponent as sputnik_045 } from '../../illustrations/045-sputnik.svg';
export { ReactComponent as stars_046 } from '../../illustrations/046-stars.svg';
export { ReactComponent as sun_047 } from '../../illustrations/047-sun.svg';
export { ReactComponent as telescope_048 } from '../../illustrations/048-telescope 1.svg';
export { ReactComponent as ufo_049 } from '../../illustrations/049-ufo.svg';
export { ReactComponent as uranus_050 } from '../../illustrations/050-uranus.svg';
export { ReactComponent as venus_051 } from '../../illustrations/051-venus.svg';
