#
# Continues integration pipeline to test every branch.
#

name: CI

on: pull_request

env:
  CI: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Unit tests
        run: yarn test
      - name: Test types
        run: yarn test:types
      - name: Test linting
        run: yarn test:lint
      - name: Test formatting
        run: yarn test:format

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: website-assets
          path: public

  Deploy:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Download website artifacts
        uses: actions/download-artifact@v1
        with:
          name: website-assets
      - name: Print assets
        # todo: add feature-branch deployment here
        run: ls website-assets
