name: Gatsby Cloud Build

on:
  # run this workflow manually from the Actions tab
  workflow_dispatch:

  # every day at 02:00
  schedule:
    - cron: '0 2 * * *'

jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      GATSBY_BUILD_WEBHOOK_URL: ${{ secrets.GATSBY_BUILD_WEBHOOK_URL }}
    steps:
      - name: Trigger build and deployment
        run: curl -X POST $GATSBY_BUILD_WEBHOOK_URL
