name: Continous Integration

on: pull_request

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install
        run: yarn
      - name: test types
        run: yarn test:types

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install
        run: yarn
      - name: build
        run: yarn build
      - name: archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: website-assets
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
    - name: download website artifacts
      uses: actions/download-artifact@v1
      with:
        name: website-assets
    - name: print assets
      run: ls

