name: Test

on: pull_request


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Test types
        run: yarn test:types
