name: Netlify Build

on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]

jobs:
  deploy:
    if: github.event.label.name == 'deploy-me'
    runs-on: ubuntu-latest
    env:
      NETLIFY_BUILD_WEBHOOK_URL: ${{ secrets.NETLIFY_BUILD_WEBHOOK_URL }}
      PR_TITLE: ${{ github.event.pull_request.title }}
    steps:
      - name: Trigger build and deployment
        run: curl -X POST -d {} '$NETLIFY_BUILD_WEBHOOK_URL?trigger_branch=$PR_TITLE'