name: Test

on: pull_request


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      env:
        CI: true
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Test types
        run: yarn test:types
