#
# Continues integration pipeline to test every branch.
#

name: Test

on: pull_request

env:
  CI: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Unit tests
        run: yarn test
      - name: Test types
        run: yarn test:types
      - name: Test linting
        run: yarn test:lint
      - name: Test formatting
        run: yarn test:format
